# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-13 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_thortaldownload'),
    ]

    operations = [
        migrations.AddField(
            model_name='thortaldownload',
            name='last_download',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
